### ISSUE TITLE
cloud architecture diagram for this code?

### ISSUE THREAD

**Issue by hawk-kc** [oracle-quickstart/oci-enterprise-scale-baseline-landing-zone#1]
Very interested in this project, starting to review the code, but would appreciate having a cloud architecture diagram (something like https://github.com/oracle-quickstart/oci-cis-landingzone-quickstart#diagram) that gives details of what this baseline creates to compare with the code.  Probably a documentation opportunity that would be added to https://docs.oracle.com/en-us/iaas/Content/cloud-adoption-framework/landing-zone.htm.

**Comment by yupeiyang-oci** [comment]
Thanks for your suggestion! We're actually working on that and will post the architecture diagram soon.
